version: "3.9"

networks:
  ecommerce-network:
    driver: bridge

services:
  app:
    image: productservicedrehi-capstone:latest
    container_name: ecommerce-app
    depends_on:
      - mysql_prod
      - redis_prod
      - kafka_prod
      - elasticsearch_prod
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DB_URL: jdbc:mysql://mysql_prod:3306/ProductServiceDrehiCapstone?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
      DB_USER: ProductServiceDrehiCapstone_user
      DB_PASS: ${DB_PASS}
      REDIS_HOST: redis_prod
      REDIS_PORT: 6379
      KAFKA_BROKERS: kafka_prod:9092
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    ports:
      - "8080:8080"
    networks:
      - ecommerce-network

  mysql_prod:
    image: mysql:8.0
    container_name: mysql_prod
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ProductServiceDrehiCapstone
      MYSQL_USER: ProductServiceDrehiCapstone_user
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASS}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - ecommerce-network

  redis_prod:
    image: redis:7-alpine
    container_name: redis_prod
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - ecommerce-network

  zookeeper_prod:
    image: confluentinc/cp-zookeeper:7.7.0
    container_name: zookeeper_prod
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - ecommerce-network

  kafka_prod:
    image: confluentinc/cp-kafka:7.7.0
    container_name: kafka_prod
    depends_on:
      - zookeeper_prod
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper_prod:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka_prod:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
    networks:
      - ecommerce-network

  elasticsearch_prod:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0
    container_name: elasticsearch_prod
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - "9200:9200"
    networks:
      - ecommerce-network

volumes:
  mysql_data:


